export type Quote = {
    quote: string
    source: string
    type: "movie" | "book"
}

export const quotes: Quote[] = [
    { "quote": "Açıkçası canım, umurumda değil.", "source": "Rüzgar Gibi Geçti", "type": "movie" },
    { "quote": "Ona reddedemeyeceği bir teklifte bulunacağım.", "source": "Baba", "type": "movie" },
    { "quote": "Toto, sanırım artık Kansas'ta değiliz.", "source": "Oz Büyücüsü", "type": "movie" },
    { "quote": "Sağlıcakla kal, dostum.", "source": "Kazablanka", "type": "movie" },
    { "quote": "Hadi bakalım, günümü güzelleştir.", "source": "Sudden Impact", "type": "movie" },
    { "quote": "Güç seninle olsun.", "source": "Yıldız Savaşları", "type": "movie" },
    { "quote": "Benimle mi konuşuyorsun?", "source": "Taksi Şoförü", "type": "movie" },
    { "quote": "Sabahın napalm kokusunu severim.", "source": "Kıyamet", "type": "movie" },
    { "quote": "E.T. eve telefon ediyor.", "source": "E.T.: Uzaylı", "type": "movie" },
    { "quote": "Çıldırdım ve artık buna katlanmayacağım!", "source": "Network", "type": "movie" },
    { "quote": "Bir nüfus sayımcısı beni test etmeye çalışmıştı. Karaciğerini bakla ve güzel bir Chianti ile yedim.", "source": "Kuzuların Sessizliği", "type": "movie" },
    { "quote": "Bond. James Bond.", "source": "Dr. No", "type": "movie" },
    { "quote": "Ev kadar güzel yer yok.", "source": "Oz Büyücüsü", "type": "movie" },
    { "quote": "Parayı göster bana!", "source": "Jerry Maguire", "type": "movie" },
    { "quote": "Gerçeği kaldıramazsın!", "source": "Birkaç İyi Adam", "type": "movie" },
    { "quote": "Her şeye rağmen, yarın yeni bir gündür!", "source": "Rüzgar Gibi Geçti", "type": "movie" },
    { "quote": "Ben de onun istediğini istiyorum.", "source": "Harry Sally'yi Tanıyınca...", "type": "movie" },
    { "quote": "Daha büyük bir tekneye ihtiyacın var.", "source": "Köpekbalığı", "type": "movie" },
    { "quote": "Geri döneceğim.", "source": "Terminatör", "type": "movie" },
    { "quote": "Hayat bir kutu çikolata gibidir. Ne çıkacağını bilemezsin.", "source": "Forrest Gump", "type": "movie" },
    { "quote": "Paris hep bizimle olacak.", "source": "Kazablanka", "type": "movie" },
    { "quote": "Ölüleri görüyorum.", "source": "Altıncı His", "type": "movie" },
    { "quote": "Hep yabancıların iyiliğine muhtaç oldum.", "source": "Arzulunan Tramvay", "type": "movie" },
    { "quote": "Hasta la vista, bebek.", "source": "Terminatör 2: Kıyamet Günü", "type": "movie" },
    { "quote": "HAL, kapı kilidini aç.", "source": "2001: Bir Uzay Macerası", "type": "movie" },
    { "quote": "Ciddi olduğumu sanıyorum. Ve bana Shirley deme.", "source": "Airplane!", "type": "movie" },
    { "quote": "Açgözlülük, daha iyi bir kelime bulamazsak, iyidir.", "source": "Wall Street", "type": "movie" },
    { "quote": "Dostlarını yakın tut; düşmanlarını daha da yakın.", "source": "Baba II", "type": "movie" },
    { "quote": "Küçük arkadaşımla tanışın!", "source": "Scarface", "type": "movie" },
    { "quote": "İşte Johnny geliyor!", "source": "Cinnet", "type": "movie" },
    { "quote": "Bırak gitsin Jake. Burası Chinatown.", "source": "Chinatown", "type": "movie" },
    { "quote": "Soylent Green insanlardan yapılıyor!", "source": "Soylent Green", "type": "movie" },
    { "quote": "Pençelerini üzerimden çek, seni pis maymun!", "source": "Maymunlar Cehennemi", "type": "movie" },
    { "quote": "Dünyanın bütün meyhane, bütün kasabaları, bütün şehirleri varken o gelip benimkine giriyor.", "source": "Kazablanka", "type": "movie" },
    { "quote": "Houston, bir sorunumuz var.", "source": "Apollo 13", "type": "movie" },
    { "quote": "Kimse Baby'yi köşeye sıkıştıramaz.", "source": "Kirli Dans", "type": "movie" },
    { "quote": "Ben dünyanın kralıyım!", "source": "Titanik", "type": "movie" },
    { "quote": "Carpe diem. Günü yakala, çocuklar. Hayatınızı olağanüstü kılın.", "source": "Ölü Ozanlar Derneği", "type": "movie" },
    { "quote": "'Merhaba' dediğinde zaten beni kazanmıştın.", "source": "Jerry Maguire", "type": "movie" },
    { "quote": "Bir martini. Çalkalanmış, karıştırılmamış.", "source": "Goldfinger", "type": "movie" },
    { "quote": "Benim preciousum.", "source": "Yüzüklerin Efendisi: İki Kule", "type": "movie" },
    { "quote": "Geçemezsin!", "source": "Yüzüklerin Efendisi: Yüzük Kardeşliği", "type": "movie" },
    { "quote": "Neden bu kadar ciddisin?", "source": "Kara Şövalye", "type": "movie" },
    { "quote": "Eğlenmiyor musunuz?", "source": "Gladyatör", "type": "movie" },
    { "quote": "Canımızı alabilirler; ama özgürlüğümüzü asla!", "source": "Cesur Yürek", "type": "movie" },
    { "quote": "Dövüş Kulübü'nün birinci kuralı: Dövüş Kulübü hakkında konuşmazsın.", "source": "Dövüş Kulübü", "type": "movie" },
    { "quote": "Ancak her şeyi kaybettikten sonra istediğimizi yapabiliriz.", "source": "Dövüş Kulübü", "type": "movie" },
    { "quote": "Sen bir büyücüsün, Harry.", "source": "Harry Potter ve Felsefe Taşı", "type": "movie" },
    { "quote": "Kendimi şanslı hissediyor muyum? Ne dersin, serseri?", "source": "Kirli Harry", "type": "movie" },
    { "quote": "Burada iletişim sorunu var.", "source": "Cool Hand Luke", "type": "movie" },
    { "quote": "Gül goncası.", "source": "Yurttaş Kane", "type": "movie" },
    { "quote": "Louis, sanırım güzel bir dostluğun başlangıcındayız.", "source": "Kazablanka", "type": "movie" },
    { "quote": "Hayır, hayır. Uçaklar değildi. Güzellik Canavarı öldürdü.", "source": "King Kong", "type": "movie" },
    { "quote": "Yaşıyor! Yaşıyor!", "source": "Frankenstein", "type": "movie" },
    { "quote": "Eğer inşa edersen, o gelecek.", "source": "Hayallerin Tarlası", "type": "movie" },
    { "quote": "Peki Bay DeMille, çekime hazırım.", "source": "Sunset Boulevard", "type": "movie" },
    { "quote": "Düşlerin yapıldığı şey.", "source": "Malta Şahini", "type": "movie" },
    { "quote": "Bayan Robinson, beni baştan çıkarmaya mı çalışıyorsunuz?", "source": "Mezun", "type": "movie" },
    { "quote": "Mantıktan ibaret, sevgili Watson.", "source": "Sherlock Holmes'un Maceraları", "type": "movie" },
    { "quote": "Beyzbolda ağlamak olmaz!", "source": "Kendi Ligimizde", "type": "movie" },
    { "quote": "The Dude kabullenmiştir.", "source": "Büyük Lebowski", "type": "movie" },
    { "quote": "Olmak ya da olmamak; işte bütün mesele bu.", "source": "Hamlet", "type": "book" },
    { "quote": "En iyi zamanlardı, en kötü zamanlardı.", "source": "İki Şehrin Hikayesi", "type": "book" },
    { "quote": "Bütün hayvanlar eşittir; ama bazı hayvanlar diğerlerinden daha eşittir.", "source": "Hayvan Çiftliği", "type": "book" },
    { "quote": "Savaş barıştır. Özgürlük köleliktir. Cehalet güçtür.", "source": "1984", "type": "book" },
    { "quote": "Varlıklı bir bekarın bir eşe ihtiyaç duyduğu evrensel bir gerçektir.", "source": "Aşk ve Gurur", "type": "book" },
    { "quote": "Böylece akıntıya karşı kayıklara benzer biçimde, durdurmaksızın geçmişe sürükleniriz.", "source": "Muhteşem Gatsby", "type": "book" },
    { "quote": "Bir insanı gerçekten anlayabilmek için olaylara onun bakış açısıyla bakman gerekir.", "source": "Bülbülü Öldürmek", "type": "book" },
    { "quote": "Bana İsmail deyin.", "source": "Moby Dick", "type": "book" },
    { "quote": "Nisan'ın parlak ve soğuk bir günüydü ve saatler on üçü vuruyordu.", "source": "1984", "type": "book" },
    { "quote": "Dolaşan herkes kaybolmuş değildir.", "source": "Yüzük Kardeşliği", "type": "book" },
    { "quote": "En karanlık gecenin bile sonu vardır ve güneş yeniden doğar.", "source": "Sefiller", "type": "book" },
    { "quote": "Dur bir dakika! Şu yandaki pencereden sızan ışık ne? O doğu; Juliet ise güneş.", "source": "Romeo ve Juliet", "type": "book" },
    { "quote": "Bir ismin önemi ne ki? Gül başka bir adla çağrılsa da aynı güzel kokar.", "source": "Romeo ve Juliet", "type": "book" },
    { "quote": "Her şeyden önce kendine karşı dürüst ol.", "source": "Hamlet", "type": "book" },
    { "quote": "Yarın, yarın ve yine yarın; bu ağır adımlarla sürünür gün be gün.", "source": "Macbeth", "type": "book" },
    { "quote": "Zihin kendi mekânıdır; cehennemden cennet, cennetten cehennem yaratabilir.", "source": "Kayıp Cennet", "type": "book" },
    { "quote": "Gerçekte ne olduğumuzu yeteneklerimiz değil, seçimlerimiz gösterir.", "source": "Harry Potter ve Sırlar Odası", "type": "book" },
    { "quote": "İyi organize edilmiş bir zihin için ölüm, bir sonraki büyük maceradan ibarettir.", "source": "Harry Potter ve Felsefe Taşı", "type": "book" },
    { "quote": "Hayaller içinde boğulup yaşamayı unutmak doğru değildir.", "source": "Harry Potter ve Felsefe Taşı", "type": "book" },
    { "quote": "Bir şeyi gerçekten istediğinde, tüm evren onu elde etmene yardım eder.", "source": "Simyacı", "type": "book" },
    { "quote": "Günümüzde insanlar her şeyin fiyatını bilir ama hiçbir şeyin değerini.", "source": "Dorian Gray'in Portresi", "type": "book" },
    { "quote": "Gerçek nadiren saf ve hiçbir zaman basit değildir.", "source": "Ciddi Olmanın Önemi", "type": "book" },
    { "quote": "Benim için tek gerçek insanlar delicesine yaşamak, delicesine konuşmak isteyenlerdir.", "source": "Yolda", "type": "book" },
    { "quote": "O benden çok benim. Ruhumuz neyden yapılmışsa, onunkiyle benimki aynı şeyden.", "source": "Uğultulu Tepeler", "type": "book" },
    { "quote": "Bugüne dek yaptığımın çok daha iyisini yapıyorum; bildiğim en iyi dinlenceye kavuşuyorum.", "source": "İki Şehrin Hikayesi", "type": "book" },
    { "quote": "Geçmişi kim kontrol ederse geleceği kontrol eder. Şimdiyi kim kontrol ederse geçmişi kontrol eder.", "source": "1984", "type": "book" },
    { "quote": "Geçmiş asla ölmez. Hatta geçmiş bile değildir.", "source": "Bir Rahibe İçin Requiem", "type": "book" },
    { "quote": "Hiçbir haritada yer almaz; gerçek yerler hiç almaz.", "source": "Moby Dick", "type": "book" },
    { "quote": "Dikkatli ol; ben korkusuzum ve bu yüzden güçlüyüm.", "source": "Frankenstein", "type": "book" },
    { "quote": "Ormanın köşende oturup başkalarının sana gelmesini bekleyemezsin.", "source": "Winnie-the-Pooh", "type": "book" },
    { "quote": "Büyükler hiçbir şeyi kendi başlarına anlayamazlar; çocukların onlara her şeyi açıklamak zorunda kalması çok yorucu.", "source": "Küçük Prens", "type": "book" },
    { "quote": "Bir insanın hayatındaki en yalnız an, tüm dünyasının çöküşünü seyredip sadece donup kalabildiği andır.", "source": "Muhteşem Gatsby", "type": "book" },
    { "quote": "Derin bir nefes aldım ve kalbimin eski övünçlü sesini dinledim: Varım, varım, varım.", "source": "Cam Fanus", "type": "book" },
    { "quote": "Soru soran yıllar vardır, cevap veren yıllar.", "source": "Gözleri Tanrı'ya Dikili", "type": "book" },
    { "quote": "Bir insanın nasıl biri olduğunu anlamak istiyorsan, onun aşağılarına nasıl davrandığına iyi bak.", "source": "Harry Potter ve Ateş Kadehi", "type": "book" },
    { "quote": "O okurken aşık oldum; uykuya dalar gibi: yavaş yavaş, sonra birden.", "source": "Aynı Yıldızın Altında", "type": "book" },
    { "quote": "Gözyaşlarımızdan utanmamıza gerek yok.", "source": "Büyük Umutlar", "type": "book" },
    { "quote": "İyi ya da kötü diye bir şey yoktur; düşünen zihin öyle yapar.", "source": "Hamlet", "type": "book" },
    { "quote": "Mutlu aileler birbirine benzer; mutsuz her aile kendi biçiminde mutsuzdur.", "source": "Anna Karenina", "type": "book" },
    { "quote": "Okuyucu, onunla evlendim.", "source": "Jane Eyre", "type": "book" },
    { "quote": "Önemli olan ne olarak doğduğun değil, ne olarak büyüdüğündür.", "source": "Harry Potter ve Ateş Kadehi", "type": "book" },
    { "quote": "En derin acıyı hisseden, mutluluğun zirvesini yaşamaya en hazır olandır.", "source": "Monte Kristo Kontu", "type": "book" },
    { "quote": "İnsan bilincinin derinliklerinde mantıklı bir evrene duyulan köklü bir ihtiyaç vardır.", "source": "Dune", "type": "book" },
    { "quote": "Fırtınalardan korkmuyorum; gemimi sürmeyi öğreniyorum çünkü.", "source": "Küçük Kadınlar", "type": "book" },
    { "quote": "Acı içindeyken mutlu günleri hatırlamaktan daha büyük üzüntü yoktur.", "source": "İlahi Komedya", "type": "book" },
    { "quote": "Mutluluk bir armağandır; püf noktası onu beklemek değil, geldiğinde sevinmektir.", "source": "Nicholas Nickleby", "type": "book" },
    { "quote": "Kimileri büyük doğar, kimileri büyüklüğe ulaşır, kimileri üzerine büyüklük yıkılır.", "source": "On İkinci Gece", "type": "book" },
    { "quote": "Hepimiz burada deliyiz.", "source": "Alice Harikalar Diyarında", "type": "book" },
    { "quote": "Kaderimimin efendisiyim, ruhumun kaptanıyım.", "source": "Invictus", "type": "book" },
    { "quote": "Ormanda iki yol ayrıldı ve ben, daha az yürünmüş olanı seçtim.", "source": "Tutulmayan Yol", "type": "book" },
    { "quote": "Hayal edebiliyorsan, yapabilirsin.", "source": "Oz Büyücüsü (roman)", "type": "book" },
    { "quote": "Başlangıçta Söz vardı.", "source": "İncil (Yuhanna 1:1)", "type": "book" },
    { "quote": "Mantıktan ibaret, sevgili Watson.", "source": "Sherlock Holmes'un Dönüşü", "type": "book" },
]

export function getDailyQuote(): Quote {
    const now = new Date()
    const start = new Date(now.getFullYear(), 0, 0)
    const diff = now.getTime() - start.getTime()
    const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24))
    return quotes[dayOfYear % quotes.length]
}
