apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  selector:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
