FROM node:20-alpine

WORKDIR /app

# Install openssl for Prisma
RUN apk update && apk add openssl

COPY package.json package-lock.json ./
RUN npm install

COPY . .

# Generate prisma client during build just in case
RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "dev"]
